### ISSUE TITLE
Is a realease planned soon

### ISSUE THREAD

**Issue by PubliAlex** [snipiba/oc-mediafinderdatabanks#1]
Hello,

I really liked your module to browse image from different library for october 2 and I'm very excited to see what you are planning for october 3.

Do you have a time estimate about a release of that new version ?

Thank you

Alex

**Comment by snipiba** [comment]
> bump, is the module still in development ?

yup. still on development... tooo many changes on multiple places like editor, mediafinder, etc. tried to create a custom editor button to search directly from richeditor, etc.

**Comment by PubliAlex** [comment]
Thank you, I'm really excited to test that when it's ready

**Comment by snipiba** [comment]
> Thank you, I'm really excited to test that when it's ready

currently, new version waiting for approval on ocm site. hope, u will like it.
